#!/usr/bin/env python3
"""Generate a requirement-coverage report for the pacto-bot-api daemon.

Parses the implementation plan in docs/plans/2026-06-24-001-feat-pacto-bot-api-daemon-plan.md,
reads the manual coverage mapping in requirements/coverage.json, and writes:

- requirements/report.md   (human-readable markdown report)
- requirements/report.json (machine-readable JSON report)

Exit code is non-zero when any requirement R1-R37 lacks both a covering test and
an explicit justification.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
PLAN_PATH = REPO_ROOT / "docs" / "plans" / "2026-06-24-001-feat-pacto-bot-api-daemon-plan.md"
MAPPING_PATH = REPO_ROOT / "requirements" / "coverage.json"
REPORT_MD_PATH = REPO_ROOT / "requirements" / "report.md"
REPORT_JSON_PATH = REPO_ROOT / "requirements" / "report.json"

REQUIREMENT_RE = re.compile(r"^- (R\d+)\.\s+(.*)$")


def parse_requirements(plan_text: str) -> dict[str, str]:
    """Extract requirement IDs and one-line summaries from the plan."""
    requirements: dict[str, str] = {}
    in_requirements_section = False

    for line in plan_text.splitlines():
        if line.strip() == "## Requirements":
            in_requirements_section = True
            continue
        if in_requirements_section and line.startswith("## "):
            break
        if not in_requirements_section:
            continue

        match = REQUIREMENT_RE.match(line)
        if match:
            req_id, description = match.groups()
            # Truncate to first sentence / 200 chars for the summary line.
            summary = description.strip()
            if len(summary) > 200:
                summary = summary[:197] + "..."
            requirements[req_id] = summary

    return requirements


def load_mapping(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def normalize_coverage(req_id: str, entry: Any) -> dict[str, Any]:
    """Return a normalized coverage entry with defaults."""
    if entry is None:
        return {"tests": [], "sources": [], "justification": None}
    if isinstance(entry, list):
        return {"tests": entry, "sources": [], "justification": None}
    if isinstance(entry, dict):
        return {
            "tests": entry.get("tests", []),
            "sources": entry.get("sources", []),
            "justification": entry.get("justification"),
        }
    raise ValueError(f"Invalid coverage entry for {req_id}: {entry!r}")


def verify_paths(req_id: str, paths: list[str]) -> list[str]:
    """Return warnings for paths that do not exist in the repo."""
    warnings: list[str] = []
    for p in paths:
        resolved = REPO_ROOT / p
        if not resolved.exists():
            warnings.append(f"{req_id}: referenced path does not exist: {p}")
    return warnings


def build_report(requirements: dict[str, str], mapping: dict[str, Any]) -> dict[str, Any]:
    entries: list[dict[str, Any]] = []
    uncovered: list[str] = []
    warnings: list[str] = []

    for req_id in sorted(requirements, key=lambda r: int(r[1:])):
        summary = requirements[req_id]
        raw = mapping.get(req_id)
        cov = normalize_coverage(req_id, raw)

        has_tests = bool(cov["tests"])
        has_sources = bool(cov["sources"])
        has_justification = bool(cov["justification"])
        covered = has_tests or has_sources or has_justification
        if not covered:
            uncovered.append(req_id)

        warnings.extend(verify_paths(req_id, cov["tests"]))
        warnings.extend(verify_paths(req_id, cov["sources"]))

        entries.append(
            {
                "id": req_id,
                "summary": summary,
                "tests": cov["tests"],
                "sources": cov["sources"],
                "justification": cov["justification"],
                "covered": covered,
            }
        )

    total = len(entries)
    covered_count = total - len(uncovered)

    return {
        "generated_by": "scripts/generate_requirement_coverage.py",
        "total_requirements": total,
        "covered_requirements": covered_count,
        "uncovered_requirements": uncovered,
        "path_warnings": warnings,
        "coverage": entries,
    }


def write_json(report: dict[str, Any]) -> None:
    REPORT_JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    with REPORT_JSON_PATH.open("w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)
        f.write("\n")


def write_markdown(report: dict[str, Any]) -> None:
    lines: list[str] = [
        "# Requirement Coverage Report",
        "",
        f"**Generated by:** `{report['generated_by']}`",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Total requirements | {report['total_requirements']} |",
        f"| Covered requirements | {report['covered_requirements']} |",
        f"| Uncovered requirements | {len(report['uncovered_requirements'])} |",
        "",
    ]

    if report["uncovered_requirements"]:
        lines.extend(
            [
                "## Uncovered Requirements",
                "",
                "The following requirements have no covering tests, sources, or justification:",
                "",
            ]
        )
        for req_id in report["uncovered_requirements"]:
            entry = next(e for e in report["coverage"] if e["id"] == req_id)
            lines.append(f"- **{req_id}** — {entry['summary']}")
        lines.append("")

    if report["path_warnings"]:
        lines.extend(
            [
                "## Path Warnings",
                "",
            ]
        )
        for warning in report["path_warnings"]:
            lines.append(f"- {warning}")
        lines.append("")

    lines.extend(
        [
            "## Coverage by Requirement",
            "",
            "| ID | Summary | Tests | Sources | Justification | Status |",
            "|---|---|---|---|---|---|",
        ]
    )

    for entry in report["coverage"]:
        status = "✅ covered" if entry["covered"] else "❌ uncovered"
        tests = "<br>".join(entry["tests"]) if entry["tests"] else "—"
        sources = "<br>".join(entry["sources"]) if entry["sources"] else "—"
        justification = entry["justification"] or "—"
        lines.append(
            f"| {entry['id']} | {entry['summary']} | {tests} | {sources} | {justification} | {status} |"
        )

    lines.append("")

    REPORT_MD_PATH.parent.mkdir(parents=True, exist_ok=True)
    with REPORT_MD_PATH.open("w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main() -> int:
    if not PLAN_PATH.exists():
        print(f"error: plan not found at {PLAN_PATH}", file=sys.stderr)
        return 1

    plan_text = PLAN_PATH.read_text(encoding="utf-8")
    requirements = parse_requirements(plan_text)

    expected_ids = {f"R{i}" for i in range(1, 38)}
    missing_ids = expected_ids - set(requirements)
    if missing_ids:
        print(
            f"error: plan is missing expected requirement IDs: {sorted(missing_ids)}",
            file=sys.stderr,
        )
        return 1

    mapping = load_mapping(MAPPING_PATH) if MAPPING_PATH.exists() else {}

    report = build_report(requirements, mapping)
    write_json(report)
    write_markdown(report)

    print(f"Wrote {REPORT_MD_PATH}")
    print(f"Wrote {REPORT_JSON_PATH}")

    if report["path_warnings"]:
        print("\nPath warnings:", file=sys.stderr)
        for warning in report["path_warnings"]:
            print(f"  - {warning}", file=sys.stderr)

    if report["uncovered_requirements"]:
        print(
            f"\nerror: {len(report['uncovered_requirements'])} requirement(s) uncovered: "
            f"{', '.join(report['uncovered_requirements'])}",
            file=sys.stderr,
        )
        return 1

    coverage_pct = (report["covered_requirements"] / report["total_requirements"]) * 100
    print(f"\nAll {report['total_requirements']} requirements covered ({coverage_pct:.0f}%).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
