repos:
  primary: "."
  additional:
    - "/Users/opselite/.beads-planning"

export.auto: true

sync.remote: "git+ssh://git@github.com/logicminds/pacto-bot-api.git"

federation.remote: "https://doltremoteapi.dolthub.com/opselite/pacto-bot-api"